-- Painel administrativo FS Fit
-- Execute esta migração no Supabase para habilitar as operações administrativas.

create table if not exists public.admin_auditoria (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete restrict,
  user_id uuid references auth.users(id) on delete set null,
  acao text not null,
  valor_anterior jsonb,
  valor_novo jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_auditoria enable row level security;

create or replace function public.fsfit_is_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.platform_admins pa where pa.user_id = p_user_id
  );
$$;

revoke all on function public.fsfit_is_admin(uuid) from public;
grant execute on function public.fsfit_is_admin(uuid) to authenticated;

create policy "Admins podem ler auditoria"
on public.admin_auditoria
for select
to authenticated
using (public.fsfit_is_admin(auth.uid()));

create or replace function public.fsfit_admin_listar_usuarios()
returns table(
  id uuid,
  nome text,
  email text,
  plano text,
  ativo boolean,
  trial_inicio timestamptz,
  trial_fim timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.fsfit_is_admin(auth.uid()) then
    raise exception 'Acesso administrativo negado';
  end if;

  return query
  select
    p.id,
    p.nome::text,
    u.email::text,
    p.plano::text,
    p.ativo,
    p.trial_inicio,
    p.trial_fim,
    u.created_at
  from public.perfis p
  left join auth.users u on u.id = p.id
  order by u.created_at desc nulls last, p.nome;
end;
$$;

revoke all on function public.fsfit_admin_listar_usuarios() from public;
grant execute on function public.fsfit_admin_listar_usuarios() to authenticated;

create or replace function public.fsfit_admin_atualizar_plano(p_user_id uuid, p_plano text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_anterior text;
begin
  if not public.fsfit_is_admin(auth.uid()) then
    raise exception 'Acesso administrativo negado';
  end if;

  select plano::text into v_anterior from public.perfis where id = p_user_id;
  if not found then raise exception 'Usuário não encontrado'; end if;

  execute 'update public.perfis set plano = $1 where id = $2'
  using p_plano, p_user_id;

  insert into public.admin_auditoria(admin_id,user_id,acao,valor_anterior,valor_novo)
  values(auth.uid(),p_user_id,'alterar_plano',jsonb_build_object('plano',v_anterior),jsonb_build_object('plano',p_plano));
end;
$$;

revoke all on function public.fsfit_admin_atualizar_plano(uuid,text) from public;
grant execute on function public.fsfit_admin_atualizar_plano(uuid,text) to authenticated;

create or replace function public.fsfit_admin_definir_conta_ativa(p_user_id uuid, p_ativo boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_anterior boolean;
begin
  if not public.fsfit_is_admin(auth.uid()) then
    raise exception 'Acesso administrativo negado';
  end if;

  select ativo into v_anterior from public.perfis where id = p_user_id;
  if not found then raise exception 'Usuário não encontrado'; end if;

  update public.perfis set ativo = p_ativo where id = p_user_id;

  insert into public.admin_auditoria(admin_id,user_id,acao,valor_anterior,valor_novo)
  values(auth.uid(),p_user_id,'alterar_status_conta',jsonb_build_object('ativo',v_anterior),jsonb_build_object('ativo',p_ativo));
end;
$$;

revoke all on function public.fsfit_admin_definir_conta_ativa(uuid,boolean) from public;
grant execute on function public.fsfit_admin_definir_conta_ativa(uuid,boolean) to authenticated;

-- Retorna pagamentos reais quando existir public.pagamentos.
-- Não estima faturamento quando a integração financeira ainda não estiver configurada.
create or replace function public.fsfit_admin_listar_pagamentos()
returns table(
  id text,
  user_id text,
  nome text,
  email text,
  plano text,
  valor numeric,
  amount numeric,
  status text,
  paid_at timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.fsfit_is_admin(auth.uid()) then
    raise exception 'Acesso administrativo negado';
  end if;

  if to_regclass('public.pagamentos') is null then
    return;
  end if;

  return query execute $q$
    select
      pg.id::text,
      pg.user_id::text,
      p.nome::text,
      u.email::text,
      coalesce(pg.plano::text, p.plano::text),
      pg.valor::numeric,
      pg.valor::numeric as amount,
      pg.status::text,
      pg.paid_at::timestamptz,
      pg.created_at::timestamptz
    from public.pagamentos pg
    left join public.perfis p on p.id = pg.user_id
    left join auth.users u on u.id = pg.user_id
    order by pg.created_at desc
  $q$;
exception
  when undefined_column then
    raise exception 'A tabela public.pagamentos existe, mas não possui as colunas esperadas: id, user_id, plano, valor, status, paid_at e created_at.';
end;
$$;

revoke all on function public.fsfit_admin_listar_pagamentos() from public;
grant execute on function public.fsfit_admin_listar_pagamentos() to authenticated;

notify pgrst, 'reload schema';