import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

const allowedOrigins=new Set(["https://fit.fssolucoes.tech",...String(Deno.env.get("FSFIT_ALLOWED_ORIGINS")||"").split(",").map(v=>v.trim()).filter(Boolean)]);
const cors=(r:Request)=>{const o=r.headers.get("origin")||"";return{"Access-Control-Allow-Origin":allowedOrigins.has(o)?o:"https://fit.fssolucoes.tech","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}};
const okOrigin=(r:Request)=>!r.headers.get("origin")||allowedOrigins.has(r.headers.get("origin")||"");
const json=(r:Request,d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"no-store"}});
const env=(n:string)=>{const v=Deno.env.get(n);if(!v)throw new Error(`Secret ausente: ${n}`);return v};
const base=()=>String(Deno.env.get("EFI_ENV")||"production").toLowerCase().startsWith("prod")?"https://cobrancas.api.efipay.com.br":"https://cobrancas-h.api.efipay.com.br";
const digits=(v:unknown)=>String(v||"").replace(/\D/g,"");
const required=(v:unknown,l:string)=>{const t=String(v||"").trim();if(!t)throw new Error(`${l} é obrigatório.`);return t};
async function token(){const a=btoa(`${env("EFI_CLIENT_ID")}:${env("EFI_CLIENT_SECRET")}`);const r=await fetch(`${base()}/v1/authorize`,{method:"POST",headers:{Authorization:`Basic ${a}`,"Content-Type":"application/json"},body:JSON.stringify({grant_type:"client_credentials"})});const p=await r.json().catch(()=>({}));const t=p?.access_token||p?.data?.access_token;if(!r.ok||!t)throw new Error(p?.error_description||p?.message||"Falha na autorização Efí");return String(t)}
async function efi(path:string,options:RequestInit={}){const t=await token();const r=await fetch(`${base()}${path}`,{...options,headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json",...(options.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok||(p?.code&&Number(p.code)>=400))throw new Error(p?.error_description||p?.message||p?.data?.message||"Erro na Efí");return p}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return okOrigin(req)?new Response("ok",{headers:cors(req)}):json(req,{erro:"Origem não autorizada"},403);
 if(req.method!=="POST")return json(req,{erro:"Método não permitido"},405);
 if(!okOrigin(req))return json(req,{erro:"Origem não autorizada"},403);
 let admin:any=null,userId:string|null=null,subscriptionId:number|null=null;
 try{
  const auth=req.headers.get("Authorization")||"";const userClient=createClient(env("SUPABASE_URL"),env("SUPABASE_ANON_KEY"),{global:{headers:{Authorization:auth}}});
  const {data:u,error:ue}=await userClient.auth.getUser();if(ue||!u.user)return json(req,{erro:"Não autenticado"},401);userId=u.user.id;
  admin=createClient(env("SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"));
  const {data:rate,error:re}=await admin.rpc("fsfit_consumir_rate_limit_assinatura",{p_escopo:"criar_cartao",p_sujeito:userId,p_limite:2,p_janela_segundos:120});if(re)throw re;if(!rate)return json(req,{erro:"Aguarde antes de tentar criar outra assinatura."},429);
  const {data:block}=await admin.from("incidentes_financeiros").select("id").eq("personal_id",userId).in("tipo",["cartao_orfao","cartao_divergente"]).in("status",["pendente","em_analise"]).limit(1).maybeSingle();if(block)return json(req,{erro:"Existe uma divergência financeira em análise."},409);
  const b=await req.json().catch(()=>({}));const planoId=required(b?.plano_id,"Plano"),paymentToken=required(b?.payment_token,"Token de pagamento"),mask=String(b?.cartao_mascara||"").trim()||null;
  const c=b?.customer||{},a=b?.billing_address||{},cpf=digits(c.cpf),phone=digits(c.phone_number),cep=digits(a.zipcode),uf=String(a.state||"").trim().toUpperCase();if(cpf.length!==11||phone.length<10||phone.length>11||cep.length!==8||!/^[A-Z]{2}$/.test(uf))return json(req,{erro:"Dados do titular ou endereço inválidos."},400);
  const {data:plan,error:pe}=await admin.from("planos_assinatura").select("id,nome,valor_centavos,intervalo_meses,efi_plan_id").eq("id",planoId).eq("ativo",true).eq("meio_pagamento","cartao").single();if(pe||!plan)return json(req,{erro:"Plano de cartão inválido."},400);
  const {data:existing}=await admin.from("assinaturas").select("id").eq("personal_id",userId).eq("meio_pagamento","cartao").eq("renovacao_automatica",true).in("status",["pendente","ativa"]).limit(1).maybeSingle();if(existing)return json(req,{erro:"Já existe assinatura recorrente ativa ou em processamento."},409);
  let planEfi=plan.efi_plan_id?Number(plan.efi_plan_id):null;if(!planEfi){const cp=await efi("/v1/plan",{method:"POST",body:JSON.stringify({name:plan.nome,interval:Math.max(Number(plan.intervalo_meses)||1,1),repeats:null})});planEfi=Number(cp?.data?.plan_id);if(!Number.isSafeInteger(planEfi))throw new Error("Plano Efí sem identificador válido");const {error:save}=await admin.from("planos_assinatura").update({efi_plan_id:planEfi,updated_at:new Date().toISOString()}).eq("id",plan.id);if(save)throw save}
  const created=await efi(`/v1/plan/${planEfi}/subscription/one-step`,{method:"POST",body:JSON.stringify({items:[{name:plan.nome,value:Number(plan.valor_centavos),amount:1}],metadata:{custom_id:`fsfit:${userId}:${plan.id}`,notification_url:String(Deno.env.get("EFI_BILLING_NOTIFICATION_URL")||`${env("SUPABASE_URL")}/functions/v1/webhook-efi-cobrancas`)},payment:{credit_card:{customer:{name:required(c.name,"Nome"),cpf,email:required(c.email,"E-mail"),birth:required(c.birth,"Nascimento"),phone_number:phone},payment_token:paymentToken,billing_address:{street:required(a.street,"Rua"),number:required(a.number,"Número"),neighborhood:required(a.neighborhood,"Bairro"),zipcode:cep,city:required(a.city,"Cidade"),complement:String(a.complement||"").trim(),state:uf}}}})});
  subscriptionId=Number(created?.data?.subscription_id);const chargeId=Number(created?.data?.charge?.id),chargeStatus=String(created?.data?.charge?.status||"waiting");if(!Number.isSafeInteger(subscriptionId)||!Number.isSafeInteger(chargeId))throw new Error("A Efí não retornou os identificadores esperados.");
  const {data:assinatura,error:ae}=await admin.from("assinaturas").insert({personal_id:userId,plano_id:plan.id,provedor:"efi",preco_contratado_centavos:Number(plan.valor_centavos),status:"pendente",efi_subscription_id:subscriptionId,efi_charge_id:chargeId,ultima_cobranca_status:chargeStatus,periodicidade_meses:Math.max(Number(plan.intervalo_meses)||1,1),renovacao_automatica:true,meio_pagamento:"cartao",cartao_mascara:mask,updated_at:new Date().toISOString()}).select("id,status,renovacao_automatica,meio_pagamento").single();
  if(ae||!assinatura){let compensated=false;try{await efi(`/v1/subscription/${subscriptionId}/cancel`,{method:"PUT"});compensated=true}catch{}
   if(!compensated)await admin.rpc("fsfit_registrar_incidente_financeiro",{p_personal_id:userId,p_origem:"criar-assinatura-cartao-fsfit",p_tipo:"cartao_orfao",p_referencia_externa:String(subscriptionId),p_codigo_erro:"INSERT_ASSINATURA_FALHOU",p_mensagem:ae?.message||"Falha local",p_contexto:{plano_id:plan.id,charge_id:chargeId}});
   await admin.rpc("fsfit_registrar_evento_financeiro",{p_personal_id:userId,p_origem:"criar-assinatura-cartao-fsfit",p_tipo_evento:compensated?"cartao_compensado_apos_falha_local":"cartao_orfao_detectado",p_referencia_externa:String(subscriptionId),p_assinatura_id:null,p_cobranca_id:null,p_status_anterior:null,p_status_novo:chargeStatus,p_sucesso:compensated,p_codigo_erro:"INSERT_ASSINATURA_FALHOU",p_mensagem_resumida:ae?.message||"Falha local"});throw new Error(compensated?"A assinatura remota foi cancelada com segurança. Tente novamente.":"Divergência financeira detectada. Não repita a operação.")}
  const {error:ce}=await admin.from("cobrancas_cartao").insert({assinatura_id:assinatura.id,personal_id:userId,plano_id:plan.id,efi_subscription_id:subscriptionId,efi_charge_id:chargeId,status:chargeStatus,valor_centavos:Number(plan.valor_centavos),payload_efi:created});if(ce)await admin.rpc("fsfit_registrar_incidente_financeiro",{p_personal_id:userId,p_origem:"criar-assinatura-cartao-fsfit",p_tipo:"cobranca_cartao_nao_registrada",p_referencia_externa:String(chargeId),p_codigo_erro:"INSERT_COBRANCA_FALHOU",p_mensagem:ce.message,p_contexto:{assinatura_id:assinatura.id,subscription_id:subscriptionId}});
  await admin.rpc("fsfit_registrar_evento_financeiro",{p_personal_id:userId,p_origem:"criar-assinatura-cartao-fsfit",p_tipo_evento:"assinatura_cartao_criada",p_referencia_externa:String(subscriptionId),p_assinatura_id:assinatura.id,p_cobranca_id:null,p_status_anterior:null,p_status_novo:chargeStatus,p_sucesso:true,p_codigo_erro:null,p_mensagem_resumida:null});
  return json(req,{sucesso:true,assinatura:{...assinatura,cobranca_status:chargeStatus}});
 }catch(e){console.error("criar-assinatura-cartao-fsfit",e);return json(req,{erro:e instanceof Error?e.message:"Erro interno"},500)}
});