import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const allowed=new Set(["https://fit.fssolucoes.tech",...String(Deno.env.get("FSFIT_ALLOWED_ORIGINS")||"").split(",").map(v=>v.trim()).filter(Boolean)]);
const cors=(r:Request)=>{const o=r.headers.get("origin")||"";return{"Access-Control-Allow-Origin":allowed.has(o)?o:"https://fit.fssolucoes.tech","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}};
const originOk=(r:Request)=>!r.headers.get("origin")||allowed.has(r.headers.get("origin")||"");
const json=(r:Request,d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"no-store"}});
const env=(n:string)=>{const v=Deno.env.get(n);if(!v)throw new Error(`Secret ausente: ${n}`);return v};
const base=()=>String(Deno.env.get("EFI_ENV")||"production").toLowerCase().startsWith("prod")?"https://cobrancas.api.efipay.com.br":"https://cobrancas-h.api.efipay.com.br";
async function token(){const a=btoa(`${env("EFI_CLIENT_ID")}:${env("EFI_CLIENT_SECRET")}`);const r=await fetch(`${base()}/v1/authorize`,{method:"POST",headers:{Authorization:`Basic ${a}`,"Content-Type":"application/json"},body:JSON.stringify({grant_type:"client_credentials"})});const p=await r.json().catch(()=>({}));const t=p?.access_token||p?.data?.access_token;if(!r.ok||!t)throw new Error(p?.error_description||p?.message||"Falha na autorização Efí");return String(t)}
async function efi(path:string,options:RequestInit={}){const t=await token();const r=await fetch(`${base()}${path}`,{...options,headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json",...(options.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok||(p?.code&&Number(p.code)>=400))throw new Error(p?.error_description||p?.message||p?.data?.message||"Erro na Efí");return p}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return originOk(req)?new Response("ok",{headers:cors(req)}):json(req,{erro:"Origem não autorizada"},403);
 if(req.method!=="POST")return json(req,{erro:"Método não permitido"},405);if(!originOk(req))return json(req,{erro:"Origem não autorizada"},403);
 let admin:any=null,userId:string|null=null;
 try{
  const auth=req.headers.get("Authorization")||"";const uc=createClient(env("SUPABASE_URL"),env("SUPABASE_ANON_KEY"),{global:{headers:{Authorization:auth}}});const {data:u,error:ue}=await uc.auth.getUser();if(ue||!u.user)return json(req,{erro:"Não autenticado"},401);userId=u.user.id;
  admin=createClient(env("SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"));const {data:rate,error:re}=await admin.rpc("fsfit_consumir_rate_limit_assinatura",{p_escopo:"atualizar_cartao",p_sujeito:userId,p_limite:3,p_janela_segundos:120});if(re)throw re;if(!rate)return json(req,{erro:"Aguarde antes de tentar novamente."},429);
  const b=await req.json().catch(()=>({}));const id=String(b?.assinatura_id||"").trim(),paymentToken=String(b?.payment_token||"").trim(),mask=String(b?.cartao_mascara||"").trim(),planoId=String(b?.plano_id||"").trim();if(!id||(!paymentToken&&!planoId))return json(req,{erro:"Informe a assinatura e a alteração desejada."},400);
  const {data:a,error:ae}=await admin.from("assinaturas").select("id,personal_id,status,efi_subscription_id,renovacao_automatica,meio_pagamento,plano_id").eq("id",id).eq("personal_id",userId).eq("meio_pagamento","cartao").single();if(ae||!a)return json(req,{erro:"Assinatura não encontrada."},404);if(!a.renovacao_automatica||a.status==="cancelada"||!a.efi_subscription_id)return json(req,{erro:"Esta recorrência não pode ser alterada."},409);
  let plan:any=null,efiPlan:number|null=null;if(planoId){const {data:p,error:pe}=await admin.from("planos_assinatura").select("id,nome,valor_centavos,intervalo_meses,efi_plan_id").eq("id",planoId).eq("ativo",true).eq("meio_pagamento","cartao").single();if(pe||!p)return json(req,{erro:"Plano inválido."},400);plan=p;efiPlan=p.efi_plan_id?Number(p.efi_plan_id):null;if(!efiPlan){const cp=await efi("/v1/plan",{method:"POST",body:JSON.stringify({name:p.nome,interval:Math.max(Number(p.intervalo_meses)||1,1),repeats:null})});efiPlan=Number(cp?.data?.plan_id);if(!Number.isSafeInteger(efiPlan))throw new Error("Plano Efí inválido");const {error:sp}=await admin.from("planos_assinatura").update({efi_plan_id:efiPlan,updated_at:new Date().toISOString()}).eq("id",p.id);if(sp)throw sp}}
  const payload:Record<string,unknown>={};if(paymentToken)payload.payment_token=paymentToken;if(plan&&efiPlan){payload.plan_id=efiPlan;payload.items=[{name:plan.nome,value:Number(plan.valor_centavos),amount:1}]}
  const updated=await efi(`/v1/subscription/${a.efi_subscription_id}`,{method:"PUT",body:JSON.stringify(payload)});
  const local:Record<string,unknown>={updated_at:new Date().toISOString()};if(paymentToken&&mask)local.cartao_mascara=mask;if(plan){local.plano_id=plan.id;local.preco_contratado_centavos=Number(plan.valor_centavos);local.periodicidade_meses=Math.max(Number(plan.intervalo_meses)||1,1)}
  const {error:le}=await admin.from("assinaturas").update(local).eq("id",a.id).eq("personal_id",userId);
  if(le){await admin.rpc("fsfit_registrar_incidente_financeiro",{p_personal_id:userId,p_origem:"atualizar-assinatura-cartao-fsfit",p_tipo:"cartao_divergente",p_referencia_externa:String(a.efi_subscription_id),p_codigo_erro:"UPDATE_LOCAL_FALHOU",p_mensagem:le.message,p_contexto:{assinatura_id:a.id,cartao_alterado:Boolean(paymentToken),plano_anterior:a.plano_id,plano_novo:plan?.id||null}});throw new Error("Alteração confirmada pela Efí, mas entrou em reconciliação no FS Fit.")}
  await admin.rpc("fsfit_registrar_evento_financeiro",{p_personal_id:userId,p_origem:"atualizar-assinatura-cartao-fsfit",p_tipo_evento:"assinatura_cartao_atualizada",p_referencia_externa:String(a.efi_subscription_id),p_assinatura_id:a.id,p_cobranca_id:null,p_status_anterior:a.status,p_status_novo:a.status,p_sucesso:true,p_codigo_erro:null,p_mensagem_resumida:null});
  return json(req,{sucesso:true,assinatura_id:a.id,cartao_atualizado:Boolean(paymentToken),plano_atualizado:Boolean(plan),efi:updated?.data?{status:updated.data.status,next_execution:updated.data.next_execution}:undefined});
 }catch(e){console.error("atualizar-assinatura-cartao-fsfit",e);return json(req,{erro:e instanceof Error?e.message:"Erro interno"},500)}
});